name: Generic Commit Message Verifier

on:
  push:
    paths-ignore:
      - 'Courses/CS102/**'
      - 'Courses/CS104/exc/L/**'
      - 'Courses/CS104/exc/T/**'
      - '.github/**'

jobs:
  check-cmsg:
    name: Check commit message
    runs-on: ubuntu-latest
    timeout-minutes: 1
    
    steps:
      - name: ‚Üß Checkout
        uses: actions/checkout@v3
        
      - name: üí¨ Get commit message
        uses: rlespinasse/git-commit-data-action@v1
      
      - name: üóí Get commit message log
        run: git log -1 > cmsg.txt
        
      - name: üîé Regex check
        id: regex
        uses: AsasInnab/regex-action@v1
        with:
          regex_pattern: '\[(add|del|mod|rnm|mov|rft)\]'
          regex_flags: 'gm'
          search_string: '${{ env.GIT_COMMIT_MESSAGE_SUBJECT }}'
          
      - name: ‚úè Prepare issue body (regex)
        id: issue-body-reg
        if: steps.regex.outputs.first_match == ''
        run: cat cmsg.txt > issue.txt
          
      - name: ‚úç Create new issue (regex)
        id: issuer-reg
        if: steps.issue-body-reg.outcome == 'success'
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: "Regex: ${{ env.GIT_COMMIT_MESSAGE_SUBJECT }} (${{ env.GIT_COMMIT_SHORT_SHA }})"
          content-filepath: issue.txt
          labels: cm-reg
          
      - name: ‚õî Failed regex check
        if: steps.issuer-reg.outcome == 'success'
        run: exit 1